"""add pinnie purchase submission fields

Revision ID: 37da7e0d38b9
Revises: 1a2b3c4d5e6f
Create Date: 2026-07-25 21:41:19.066031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37da7e0d38b9'
down_revision = '1a2b3c4d5e6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pinnies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_declared', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('purchase_submitted_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pinnies', schema=None) as batch_op:
        batch_op.drop_column('purchase_submitted_at')
        batch_op.drop_column('payment_declared')

    # ### end Alembic commands ###
